language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease
    
    
 notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=0ccda99017197a448cce1afa85e2e9506016bb483b902f51a1c539ccb26f3f44
